/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ChatTCP;

public class App {

    public static void main(String[] args) {
        ServerInterface serverInterface = new ServerInterface();
        Thread thread = new Thread(serverInterface);
        thread.start();
    }
}
